### ISSUE TITLE
"touch" callback not working

### ISSUE THREAD

**Issue by alsino** [pierdr/Tramontana-for-Javascript#2]
Hi there,

thanks for this library! It is great! 
I had a slight problem when trying to subscribe to touch events via the subscribeTouch method. The callback was not returning for any valued fo touch methods.

I tried to retrieve the x and y value like this:

`iphone.subscribeTouch(function (ipAddress, x,y) {
    console.log(x,y);
  });`

Did I get it completely wrong? Could you maybe point me in the correct direction?

**Comment by spassvogel** [comment]
It seems the version served by https://pierdr.github.io/Tramontana-for-Javascript/lib/tramontana.js is *not* the latest version. Better to download the `tramontana.js` (not the min) and `utils.js` from github and serve them yourself.

**Comment by spassvogel** [comment]
[egueli](https://github.com/egueli) I hope I'm not asking too much but would you be able to update the version of `tramontana.js` and more importantly `tramontana_min.js` served by github pages? Such that the issue in this ticket is resolved and the added `attitude()` fn is available?

**Comment by egueli** [comment]
Thanks for the bug report @spassvogel , I'll work on a fix this weekend.

**Comment by spassvogel** [comment]
Great! Just so you know, I am guiding students of the [Hague University of Applied Science](https://www.thehagueuniversity.com/) who have started prototyping with Tramontana for JS together with P5.js and they are very enthusiastic about it :)

**Comment by egueli** [comment]
Happy to hear you and your students are happy with Tramontana!

I just updated the files on GitHub Pages as well as this repo. They should become public within a few minutes. Hope this solves the problem, so I'm closing this issue; let me know if it's still not working.
