### ISSUE TITLE
touch callback and touchdrag function not working

### ISSUE THREAD

**Issue by mrbombmusic** [pierdr/Tramontana-for-Javascript#5]
Hello,

I've been playing around with this in p5.js and when I subscribe to a touch event using subscribeTouch, the touch and touchedDown messages are received and the data is coming up in the console. However, after each time the data is logged, there is an error message which says: 
Uncaught TypeError: e.callbacks.touched is not a function
    at e.socket.onmessage (tramontana.js:6)
    at HTMLDivElement.<anonymous> (tramontana.js:6)
    at WebSocket.i.onmessage (tramontana.js:6)

The onTouchEvent callback method also gives this error message.

Additionally, the subscribeTouchDrag function also gives an error message that it is not a function and there is no data that is coming up in the console .

I have had success with the other sensor functions and callback methods.

**Comment by mjvo** [comment]
I was able to get subscribeTouch to work -  the minimized [library](https://pierdr.github.io/Tramontana-for-Javascript/lib/tramontana_min.js) linked off the tramontana.xyz site doesn't work, but [this one does](https://github.com/pierdr/Tramontana-for-Javascript/blob/master/lib/tramontana.js) when used  with the [utils.js ](https://github.com/pierdr/Tramontana-for-Javascript/blob/master/lib/utils.js).    

Javascript:

```javascript
device.subscribeTouch(gotTouch);

function gotTouch(ip, e) { // callback for subscribeTouch()
      console.log(e.x);
      console.log(e.y);
}

**Comment by mrbombmusic** [comment]
Thanks for the reply, @mjvo .

I tried with those libraries but am still getting the error message below.

```
Uncaught TypeError: e.callbacks.touched is not a function tramontana.js:6 
    at a.e.socket.onmessage (tramontana.js:6)
    at HTMLDivElement.<anonymous> (utils.js:180)
    at WebSocket.h.onmessage (utils.js:180)
```

**Comment by egueli** [comment]
Hi @mrbombmusic, 
I couldn't reproduce the issue. I can subscribe with `subscribeTouch` and can receive messages with no errors.
could you tell me more about your environment? Which browser, which mobile OS. Also how is your code that subscribes to touch events and receives them?

**Comment by mrbombmusic** [comment]
Hi @egueli,
Thanks for the reply.

I was finally able to get the `subscribeTouch` to work. However, I am still having trouble with the 
`subscribeTouchDrag`.

This is code I am using with p5.js
```
let device = new tramontana();

let touchData;

function setup() {
  createCanvas(350, 650);
  device.start("192.168.1.151", function(e) {
    if (e == undefined) {
      //SUCCESS TRAMONTANA CONNECTED
      device.makeVibrate();
      device.subscribeTouchDrag(function(ip, e) {
        gotTouch(e);
      })
    }
  });
}

function gotTouch(d) {
  touchData = Object.values(d);
  console.log(touchData);
}


function draw() {
  background(220);
  if (touchData != undefined) {
    ellipse(touchData[0], touchData[1], 24);
  }
}
```

This is the exact same code that worked with the `subscribeTouch` but gives me this error with  `subscribeTouchDrag`
```
Uncaught TypeError: device.subscribeTouchDrag is not a function
    at Object.socketopen (sketch.js:12)
    at a.object.socket.onopen (tramontana.js:82)
    at HTMLDivElement.<anonymous> (utils.js:180)
    at WebSocket.h.onopen (utils.js:180)
```

I am using a mac book air with macOS High Sierra v. 10.13.6 and an iPhone 8 w OS 13.3.1 and I have added the libraries that were link above by mjvo.
Thanks again

**Comment by egueli** [comment]
Hi @mrbombmusic , the reason why `subscribeTouchDrag` isn't working is because it was implemented in the Processing library but not yet in the JS library. I'll make a PR soon.

**Comment by mrbombmusic** [comment]
@egueli Ok. Thank you for letting me know. I'll keep an eye out for it.

**Comment by egueli** [comment]
Hi @mrbombmusic, I made and merged the PR. Feel free to test and let me know if it works for you.

**Comment by mrbombmusic** [comment]
@egueli It does work!!! Thanks for the update. this will give me something else to play with during this lockdown!
