### ISSUE TITLE
subscribeTouch on tramontana.js

### ISSUE THREAD

**Issue by canvvas** [pierdr/Tramontana-for-Javascript#7]
Hi,
im not sure if you are still working on this, but how does the subscribeTouch callback work ? It does not seem to trigger...

**Comment by pierdr** [comment]
Do other callbacks work? Is it just the subscribeTouch that doesn't? I'll investigate. @egueli did you look into this before?

**Comment by canvvas** [comment]
Thanks for answering :)
yes i tried subscribeAttitude and the callback fired. 

At first it told me that "e.callback.touched" was not a function, but i fixed that. But the callback still isnt firing.

EDIT : I think its important to mention that i use the tramontana_min.js : 
[min.js](https://pierdr.github.io/Tramontana-for-Javascript/lib/tramontana_min.js)

**Comment by canvvas** [comment]
I used an old version of tramontana and the subscribeTouch works in the most recent one.

**Comment by pierdr** [comment]
Nice to hear! Thanks for posting and experimenting.
